apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: h28ia5xee-dotnet-basic
  janus-idp.io/tekton: h28ia5xee-dotnet-basic
  backstage.io/kubernetes-id: h28ia5xee-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: h28ia5xee-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
